; Script generated by Inno Setup Script Wizard
#define MyAppName "PTEEAIAgent"
#define MyAppVersion "1.0.0"
#define MyAppPublisher ""
#define MyAppURL ""
#define MyAppExeName "PTEEAIAgent.exe"

[Setup]
AppId={{1847717e-461f-48f4-a3d7-f0b78c4b3ea5}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=.\setup
OutputBaseFilename=PTEEAIAgentSetup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
Uninstallable=yes
UninstallDisplayName={#MyAppName}
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "startmenuicon"; Description: "Create a Start Menu shortcut"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startmenuicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[Code]
var
  CustomPage: TWizardPage;
  ChromeExeEdit: TEdit;
  ChromeUserDataEdit: TEdit;
  ChromeExeLabel: TNewStaticText;
  ChromeUserDataLabel: TNewStaticText;

procedure InitializeWizard;
begin
  CustomPage := CreateCustomPage(wpWelcome, 'Additional Settings', 'Please provide the following information:');

  // Nhãn cho Chrome Executable Path
  ChromeExeLabel := TNewStaticText.Create(CustomPage);
  ChromeExeLabel.Left := 10;
  ChromeExeLabel.Top := 10;
  ChromeExeLabel.Width := 300;
  ChromeExeLabel.Height := 20;
  ChromeExeLabel.Caption := 'Chrome Executable Path:';
  ChromeExeLabel.Parent := CustomPage.Surface;

  ChromeExeEdit := TEdit.Create(CustomPage);
  ChromeExeEdit.Left := 10;
  ChromeExeEdit.Top := 30;
  ChromeExeEdit.Width := 400;
  ChromeExeEdit.Text := 'C:\Program Files\Google\Chrome\Application\chrome.exe';
  ChromeExeEdit.Parent := CustomPage.Surface;

  // Nhãn cho Chrome User Data Path
  ChromeUserDataLabel := TNewStaticText.Create(CustomPage);
  ChromeUserDataLabel.Left := 10;
  ChromeUserDataLabel.Top := 60;
  ChromeUserDataLabel.Width := 300;
  ChromeUserDataLabel.Height := 20;
  ChromeUserDataLabel.Caption := 'Chrome User Data Path:';
  ChromeUserDataLabel.Parent := CustomPage.Surface;

  ChromeUserDataEdit := TEdit.Create(CustomPage);
  ChromeUserDataEdit.Left := 10;
  ChromeUserDataEdit.Top := 80;
  ChromeUserDataEdit.Width := 400;
  ChromeUserDataEdit.Text := 'C:\Users\' + GetUserNameString + '\AppData\Local\Google\Chrome\User Data';
  ChromeUserDataEdit.Parent := CustomPage.Surface;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    RegWriteStringValue(HKCR, '{#MyAppName}\Settings', 'ChromeExePath', ChromeExeEdit.Text);
    RegWriteStringValue(HKCR, '{#MyAppName}\Settings', 'ChromeUserDataPath', ChromeUserDataEdit.Text);
  end;
end;

[Registry]
Root: HKCR; Subkey: "PTEEAIAgent"; ValueType: string; ValueName: ""; ValueData: "URL:PTEEAIAgent Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell\open"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\PTEEAIAgent"; Flags: uninsdeletekey

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"